### PR TITLE
Remove duplicates in .chezmoiexternal.yaml

### PR DESCRIPTION
**Pull request by MuXiu1997**
other ref: https://github.com/MuXiu1997/dotfiles/blob/main/.chezmoiexternal.yaml

### CODE REVIEW

**Comment by MuXiu1997** [comment]
Just a demo

**Comment by felipecrs** [comment]
Wow, this is amazing. Thank you, a lot!

I will just make some adjustments to prevent calling curl multiple times, like storing some in variables.

**Comment by felipecrs** [comment]
Oh... In fact I just realized that there is no way to store results of `template` inside a variable (https://github.com/twpayne/chezmoi/issues/1619), and thus I could not do something like:

```yaml
# Downloads all the variants of Fira Code Nerd Font
{{- $nerdFontRevision := template "gitHubHEAD" "ryanoasis/nerd-fonts" -}}
{{-   range $_, $face := list "Regular" "Light" "Medium" "Bold" "Retina" "SemiBold" -}}
{{-     range $_, $variant := list "" " Mono" }}
".local/share/fonts/Fira Code {{ $face }} Nerd Font Complete{{ $variant }}.ttf":
  type: file
  url: "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/{{ $nerdFontRevision }}/patched-fonts/FiraCode/{{ $face }}/complete/Fira%20Code%20{{ $face }}%20Nerd%20Font%20Complete{{ $variant | replace " " "%20" }}.ttf"
{{      end -}}
{{-   end -}}
```

And if I don't do that, `curl` would endup being called multiple times, which slows down the chezmoi process by a lot (and it's already very slow in my dotfiles).

So, because of that, I will wait for https://github.com/twpayne/chezmoi/issues/1619 to be implemented so that I can leverage what you did without the drawback of multiplying the number of `curl` calls.

Again, thanks a lot!

**Comment by MuXiu1997** [comment]
Here's an inelegant but workable way
[ed3c61d](https://github.com/felipecrs/dotfiles/pull/46/commits/ed3c61dbfd66ff5cb2f4149a80d710430fa2ce55)

**Comment by MuXiu1997** [comment]
By the way, in `chezmoi` 2.8.0, the `gitHubLatestRelease` template function is available and it will cache based on RFCs to avoid duplicate requests

**Comment by MuXiu1997** [comment]
Maybe it's another way, I didn't bring my computer and didn't test it
```yaml
{{- define "gitHubHEAD" }}
{{- $dict := (index . 0) }}
{{- $key := (index . 1) }}
{{-   if not (hasKey $dict $key) }}
{{-     $value := output "bash" "-c" (printf "git ls-remote https://github.com/%s.git HEAD | awk '{print $1}'" $key) | trim }}
{{-     $_ := set $dict $key $value }}
{{-     $key }}
{{-   end }}
{{- end -}}

{{- define "gitHubLatest" }}
{{- $dict := (index . 0) }}
{{- $key := (index . 1) }}
{{-   if not (hasKey $dict $key) }}
{{-     $value := output "curl" "-fsSL" "-o" "/dev/null" "-w" "%{url_effective}" (printf "https://github.com/%s/releases/latest" $key) | trim | base | trimPrefix "v" }}
{{-     $_ := set $dict $key $value }}
{{-     $key }}
{{-   end }}
{{- end -}}

{{- $HEADs := dict -}}
{{- $latests := dict -}}

".oh-my-zsh":
  type: archive
  url: "https://github.com/{{ template "gitHubHEAD" list $HEADs "ohmyzsh/ohmyzsh" }}/archive/{{ get $HEADs "ohmyzsh/ohmyzsh" }}.tar.gz"
  stripComponents: 1
  # waiting for https://github.com/twpayne/chezmoi/issues/1614#issuecomment-966524408
  # exact: true

".oh-my-zsh/custom/themes/powerlevel10k":
  type: archive
  url: "https://github.com/{{ template "gitHubHEAD" list $HEADs "romkatv/powerlevel10k" }}/archive/{{ get $HEADs "romkatv/powerlevel10k" }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-syntax-highlighting":
  type: archive
  url: "https://github.com/{{ template "gitHubHEAD" list $HEADs "zsh-users/zsh-syntax-highlighting" }}/archive/{{ get $HEADs "zsh-users/zsh-syntax-highlighting" }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-autosuggestions":
  type: archive
  url: "https://github.com/{{ template "gitHubHEAD" list $HEADs "zsh-users/zsh-autosuggestions" }}/archive/{{ get $HEADs "zsh-users/zsh-autosuggestions" }}.tar.gz"
  stripComponents: 1
  exact: true

".oh-my-zsh/custom/plugins/zsh-completions":
  type: archive
  url: "https://github.com/{{ template "gitHubHEAD" list $HEADs "zsh-users/zsh-completions" }}/archive/{{ get $HEADs "zsh-users/zsh-completions" }}.tar.gz"
  stripComponents: 1
  exact: true

{{ if not .is_devcontainer -}}
{{   if .is_gnome | and (not .is_wsl) -}}
".local/bin/gnome-shell-extension-installer":
  type: file
  url: "https://raw.githubusercontent.com/{{ template "gitHubHEAD" list $HEADs "brunelli/gnome-shell-extension-installer" }}/{{ get $HEADs "brunelli/gnome-shell-extension-installer" }}/gnome-shell-extension-installer"
  executable: true
{{-  end }}

".deno/bin/deno":
  type: file
  url: "https://github.com/{{ template "gitHubLatest" list $latests "denoland/deno" }}/releases/download/v{{ get $latests "denoland/deno" }}/deno-x86_64-unknown-linux-gnu.zip"
  executable: true
  filter:
    command: zcat

".volta/bin":
  type: archive
  url: "https://github.com/{{ template "gitHubLatest" list $latests "volta-cli/volta" }}/releases/download/v{{ get $latests "volta-cli/volta" }}/volta-{{ get $latests "volta-cli/volta" }}-linux-openssl-1.1.tar.gz"

".docker/cli-plugins/docker-compose":
  type: file
  url: "https://github.com/{{ template "gitHubLatest" list $latests "docker/compose" }}/releases/download/v{{ get $latests "docker/compose" }}/docker-compose-linux-x86_64"
  executable: true

".docker/cli-plugins/docker-buildx":
  type: file
  url: "https://github.com/{{ template "gitHubLatest" list $latests "docker/buildx" }}/releases/download/v{{ get $latests "docker/buildx" }}/buildx-v{{ get $latests "docker/buildx" }}.linux-amd64"
  executable: true

# Downloads all the variants of Fira Code Nerd Font
{{-   range $_, $face := list "Regular" "Light" "Medium" "Bold" "Retina" "SemiBold" -}}
{{-     range $_, $variant := list "" " Mono" }}
".local/share/fonts/Fira Code {{ $face }} Nerd Font Complete{{ $variant }}.ttf":
  type: file
  url: "https://raw.githubusercontent.com/{{ template "gitHubHEAD" list $HEADs "ryanoasis/nerd-fonts" }}/{{ get $HEADs "ryanoasis/nerd-fonts" }}/patched-fonts/FiraCode/{{ $face }}/complete/Fira%20Code%20{{ $face }}%20Nerd%20Font%20Complete{{ $variant | replace " " "%20" }}.ttf"
{{      end -}}
{{-   end -}}

{{- end -}}
```

**Comment by felipecrs** [comment]
You know what? This is a brilliant, despite a bit inelegant indeed.

For now, I think I will convert to `gitHubLatestRelease` because of its caching mechanism (to solve my big problem about slowness), and try in my work environment to see if I will hit the API's rate too much.

**Comment by MuXiu1997** [comment]
As long as the first call does not exceed 50 times at once, there should be no `Rate Limit`

and close

**Comment by felipecrs** [comment]
Yeah, by in my work environment, a single external IP is shared for many co-workers. But anyway, I will perform some tests...

**Comment by MuXiu1997** [comment]
Good luck~

**Pull request closed without merging**
